### ISSUE TITLE
ContaCorrenteService - correções e ajustes

### ISSUE THREAD

**Issue by JessicaNathany** [ludmylaborges/POO#1]
O método OperacaoSaque está faltando:

- Está faltando a entrada para o usuário (Console.WriteLine("Digite o valor de saque...")) digitar o  valor para o saque, deste caso você não informou o método o que ele deve calcular;

Mesma coisa se repete para o método OperacaoTransferencia e OperacaoDeposito

**Comment by JessicaNathany** [comment]
Por boas práticas, pode remover os espaços no final do método Transferir.

- método Transferir deverá ser um void

**Comment by ludmylaborges** [comment]
Eu coloquei dentro da pasta PresentationContaCorrente\Program.cs.
Ok.
