### ISSUE TITLE
Por que criou um outro projeto PresentationContaCorrente?

### ISSUE THREAD

**Issue by JessicaNathany** [ludmylaborges/POO#2]
Neste caso, não há necessidade desse projeto. Usaremos um único projeto e apenas duas pastas: Model e Service, por favor manter igual do projeto original e criar a pasta Model com as entidades Conta, ContaInvestimento e ContaCorrente

**Comment by ludmylaborges** [comment]
Eu separei o projeto de interface do usuário (presentation) do projeto que contem as regras de negócio (class library).
