### ISSUE TITLE
Classe Program.cs 

### ISSUE THREAD

**Issue by JessicaNathany** [ludmylaborges/POO#3]
Procurei a classe Program.cs e não a encontrei, nós precisamos dela. Pode mante-la no projeto conforme o projeto original

**Comment by ludmylaborges** [comment]
Eu coloquei dentro da pasta PresentationContaCorrente.

**Comment by JessicaNathany** [comment]
A instancia do objeto ContaCorrente deve ficar na classe ContaCorrenteService:

var conta = new ContaCorrente
{
     Saldo = 5000,
     Nome = "Ludmyla"
etc...
}

var contaDestino = new ContaCorrente
{
     Saldo = 5000,
     Nome = "Jéssica"
etc...
}

Mensagem ConsoleWriteLine("Digite o valor do depósito:") => deverá ficar também na classe ContaCorenteService.

A classe Program, ela só faz a chamada dos métodos OperacaoSaque, OperacaoDeposito etc.. e exibe o menu de opções somente isso deve conter
